### ISSUE TITLE
Deploy app as Docker container

### ISSUE THREAD

**Issue by scott-steadman** [scott-steadman/se-registry#22]
# Summary
I want some experience with containerized deployment

# Tasks
## Build image (bin/docker-build.sh)
- [x] create Dockerfile
- [x] tag release
- [x] copy code
- [x] bundle install
- [x] assets:precompile
- [x] create credentials files

## Run image (bin/docker-run.sh)
- [x] db:migrate
- [x] run puma

## Update README.rdoc
- [x] add build steps
- [x] add test steps
- [x] add deploy steps
