### ISSUE TITLE
Add presence functionality.

### ISSUE THREAD

**Issue by scott-steadman** [scott-steadman/se-registry#31]
# Summary
I want to see how ActionCable works.
This feature will let a user know when a friend is on the site.

# Tasks
## Back-end
- [x] create channel
- [x] publish user appearance to friends
- [x] publish user disappearance to friends
- [x] code coverage pass

## Front-end
- [x] update My Friends menu item with count when friends appear
- [x] update My Friends menu item with count when friends disappear
- [x] add hover text to describe count
